### ISSUE TITLE
Add links to student bio.

### ISSUE THREAD

**Issue by smadha** [USCDataScience/uscdatascience.github.io#4] opened 2016-02-17 19:38 UTC
@USCDataScience/website how do we want to show this? 
- Links to "http: //irds.usc.edu/profile/student_name"
- Links to github/LinkedIn
- Short description on click

**Comment by thammegowda** [comment] 2016-03-14 23:35
Duplicate of #10 , @smadha Please check the site and see if we need to enhance student details.
 Can we close this if all okay?

**Comment by smadha** [comment] 2016-03-16 18:44
Looks great @thammegowda

Thanks for adding link for everyone :)

**Closed as completed** 2016-03-16 18:45 UTC
